apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pp.fullname" . }}-api
  labels:
    {{- include "pp.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
