"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-17 11:34:42.133538
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.CheckConstraint("key IN ('admin', 'presales_gm', 'presales_director', 'account_presales')", name=op.f('ck_roles_role_key')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('key', name=op.f('uq_roles_key'))
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('director_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], name=op.f('fk_teams_director_id_users'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('director_id', name=op.f('uq_teams_director_id')),
    sa.UniqueConstraint('name', name=op.f('uq_teams_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_index('ix_users_username_lower', 'users', [sa.text('lower(username)')], unique=True)
    op.create_table('ai_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_ai_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_ai_settings'))
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_number', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('ai_readiness', sa.String(length=32), nullable=True),
    sa.Column('has_critical_findings', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ai_readiness IS NULL OR ai_readiness IN ('ready', 'ready_with_actions', 'not_ready')", name=op.f('ck_opportunities_ai_readiness')),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'in_review', 'changes_requested', 'ready_for_ai', 'ai_analysis', 'ai_recommendations', 'completed')", name=op.f('ck_opportunities_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_opportunities_created_by_users')),
    sa.ForeignKeyConstraint(['current_version_id'], ['opportunity_versions.id'], name='fk_opportunities_current_version', use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_opportunities_owner_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_opportunities_team_id_teams')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_opportunities_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('opportunity_number', name=op.f('uq_opportunities_opportunity_number'))
    )
    op.create_index('ix_opportunities_account_lower', 'opportunities', [sa.text('lower(account_name)')], unique=False)
    op.create_index(op.f('ix_opportunities_ai_readiness'), 'opportunities', ['ai_readiness'], unique=False)
    op.create_index(op.f('ix_opportunities_owner_id'), 'opportunities', ['owner_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_team_id'), 'opportunities', ['team_id'], unique=False)
    op.create_index('ix_opportunities_updated_at', 'opportunities', ['updated_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_audit_logs_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action_time', 'audit_logs', ['action', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_opportunity', 'audit_logs', ['opportunity_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_time', 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_notifications_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where='read_at IS NULL')
    op.create_table('opportunity_access',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_opportunity_access_granted_by_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_access_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opportunity_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'user_id', name=op.f('pk_opportunity_access'))
    )
    op.create_index(op.f('ix_opportunity_access_user_id'), 'opportunity_access', ['user_id'], unique=False)
    op.create_table('opportunity_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('based_on_version_id', sa.UUID(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['based_on_version_id'], ['opportunity_versions.id'], name=op.f('fk_opportunity_versions_based_on_version_id_opportunity_versions')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_opportunity_versions_created_by_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_versions_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_opportunity_versions_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_versions')),
    sa.UniqueConstraint('opportunity_id', 'version_number', name='uq_version_number')
    )
    op.create_index(op.f('ix_opportunity_versions_opportunity_id'), 'opportunity_versions', ['opportunity_id'], unique=False)
    op.create_table('ai_analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('llm_model', sa.String(length=160), nullable=True),
    sa.Column('llm_model_revision', sa.String(length=80), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('output_schema_version', sa.String(length=40), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_sha256', sa.String(length=64), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_ai_analysis_runs_status')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_ai_analysis_runs_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_ai_analysis_runs_triggered_by_users')),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_ai_analysis_runs_version_id_opportunity_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analysis_runs'))
    )
    op.create_index(op.f('ix_ai_analysis_runs_version_id'), 'ai_analysis_runs', ['version_id'], unique=False)
    op.create_index('ix_ai_runs_opp_time', 'ai_analysis_runs', ['opportunity_id', 'queued_at'], unique=False)
    op.create_table('deepdive_data',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_deepdive_data_version_id_opportunity_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_deepdive_data'))
    )
    op.create_table('director_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('changes_requested','ready_for_ai')", name=op.f('ck_director_reviews_decision')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_director_reviews_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_director_reviews_reviewer_id_users')),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_director_reviews_version_id_opportunity_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_director_reviews')),
    sa.UniqueConstraint('version_id', 'reviewer_id', name='uq_review_version_reviewer')
    )
    op.create_index(op.f('ix_director_reviews_opportunity_id'), 'director_reviews', ['opportunity_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries'))
    )
    op.create_index('ix_deliveries_pending', 'notification_deliveries', ['channel', 'status', 'next_attempt_at'], unique=False)
    op.create_table('opportunity_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('logical_document_id', sa.Uuid(), nullable=False),
    sa.Column('doc_version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('scan_status', sa.String(length=16), nullable=False),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("category IN ('rfp', 'rfi_rfq', 'scope_of_work', 'customer_requirements', 'boq', 'technical_specifications', 'customer_clarification', 'email', 'other')", name=op.f('ck_opportunity_documents_category')),
    sa.CheckConstraint("extraction_status IN ('pending','running','done','failed','not_required')", name=op.f('ck_opportunity_documents_extraction_status')),
    sa.CheckConstraint("scan_status IN ('pending','clean','infected','error','skipped')", name=op.f('ck_opportunity_documents_scan_status')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_opportunity_documents_deleted_by_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_documents_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_opportunity_documents_uploaded_by_users')),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_opportunity_documents_version_id_opportunity_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_opportunity_documents_storage_key'))
    )
    op.create_index('ix_documents_opp_active', 'opportunity_documents', ['opportunity_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_opportunity_documents_logical_document_id'), 'opportunity_documents', ['logical_document_id'], unique=False)
    op.create_index(op.f('ix_opportunity_documents_version_id'), 'opportunity_documents', ['version_id'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_workflow_history_actor_id_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_workflow_history_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_workflow_history_version_id_opportunity_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_history'))
    )
    op.create_index('ix_workflow_history_opp_time', 'workflow_history', ['opportunity_id', 'created_at'], unique=False)
    op.create_table('ai_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('evidence_class', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('suggested_owner', sa.String(length=160), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint("evidence_class IN ('fact', 'director_observation', 'ai_inference', 'missing_information')", name=op.f('ck_ai_findings_evidence_class')),
    sa.CheckConstraint("severity IN ('critical', 'high', 'medium', 'low')", name=op.f('ck_ai_findings_severity')),
    sa.ForeignKeyConstraint(['run_id'], ['ai_analysis_runs.id'], name=op.f('fk_ai_findings_run_id_ai_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_findings'))
    )
    op.create_index(op.f('ix_ai_findings_run_id'), 'ai_findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_ai_findings_severity'), 'ai_findings', ['severity'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('overall_readiness', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('readiness_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('management_recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("overall_readiness IN ('ready', 'ready_with_actions', 'not_ready')", name=op.f('ck_ai_recommendations_overall_readiness')),
    sa.ForeignKeyConstraint(['run_id'], ['ai_analysis_runs.id'], name=op.f('fk_ai_recommendations_run_id_ai_analysis_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations')),
    sa.UniqueConstraint('run_id', name=op.f('uq_ai_recommendations_run_id'))
    )
    op.create_table('review_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('comment_type', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("comment_type IN ('general', 'section', 'critical_issue', 'missing_information', 'required_action')", name=op.f('ck_review_comments_comment_type')),
    sa.CheckConstraint("priority IS NULL OR priority IN ('critical', 'high', 'medium', 'low')", name=op.f('ck_review_comments_priority')),
    sa.CheckConstraint("status IN ('open','addressed','closed')", name=op.f('ck_review_comments_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_review_comments_created_by_users')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_review_comments_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_review_comments_owner_user_id_users')),
    sa.ForeignKeyConstraint(['review_id'], ['director_reviews.id'], name=op.f('fk_review_comments_review_id_director_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_review_comments_version_id_opportunity_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_comments'))
    )
    op.create_index('ix_review_comments_opp_version', 'review_comments', ['opportunity_id', 'version_id'], unique=False)
    op.create_index(op.f('ix_review_comments_review_id'), 'review_comments', ['review_id'], unique=False)
    # ### end Alembic commands ###

    # ---- Reference data
    op.execute("""
        INSERT INTO roles (id, key, name) VALUES
          (1, 'admin', 'Admin'),
          (2, 'presales_gm', 'Presales GM'),
          (3, 'presales_director', 'Presales Director'),
          (4, 'account_presales', 'Account Presales')
    """)

    # ---- Governance guards enforced by the database, not only by application code
    op.execute("""
        CREATE OR REPLACE FUNCTION portal_block_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION '% on % is not allowed (append-only / immutable record)', TG_OP, TG_TABLE_NAME
            USING ERRCODE = 'insufficient_privilege';
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER audit_logs_append_only BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION portal_block_mutation();
    """)
    # A finished AI run is frozen: no updates, no deletes. Findings/recommendations of a finished run likewise.
    op.execute("""
        CREATE OR REPLACE FUNCTION portal_freeze_ai_run() RETURNS trigger AS $$
        BEGIN
          IF OLD.status IN ('succeeded', 'failed', 'cancelled') THEN
            RAISE EXCEPTION 'AI analysis run % is finished and immutable', OLD.id USING ERRCODE = 'insufficient_privilege';
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER ai_runs_immutable BEFORE UPDATE OR DELETE ON ai_analysis_runs
        FOR EACH ROW EXECUTE FUNCTION portal_freeze_ai_run();
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION portal_freeze_ai_children() RETURNS trigger AS $$
        DECLARE run_status text;
        BEGIN
          SELECT status INTO run_status FROM ai_analysis_runs WHERE id = COALESCE(NEW.run_id, OLD.run_id);
          IF run_status IN ('succeeded', 'failed', 'cancelled') THEN
            RAISE EXCEPTION 'Results of finished AI run are immutable' USING ERRCODE = 'insufficient_privilege';
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    for table in ("ai_findings", "ai_recommendations"):
        op.execute(f"""
            CREATE TRIGGER {table}_immutable BEFORE INSERT OR UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION portal_freeze_ai_children();
        """)
    # Locked versions keep their DeepDive content forever.
    op.execute("""
        CREATE OR REPLACE FUNCTION portal_freeze_locked_deepdive() RETURNS trigger AS $$
        BEGIN
          IF EXISTS (SELECT 1 FROM opportunity_versions v WHERE v.id = OLD.version_id AND v.is_locked) THEN
            RAISE EXCEPTION 'DeepDive of a locked version cannot change' USING ERRCODE = 'insufficient_privilege';
          END IF;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER deepdive_locked_immutable BEFORE UPDATE OR DELETE ON deepdive_data
        FOR EACH ROW EXECUTE FUNCTION portal_freeze_locked_deepdive();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS deepdive_locked_immutable ON deepdive_data")
    for table in ("ai_findings", "ai_recommendations"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    op.execute("DROP TRIGGER IF EXISTS ai_runs_immutable ON ai_analysis_runs")
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("DROP FUNCTION IF EXISTS portal_freeze_locked_deepdive, portal_freeze_ai_children, portal_freeze_ai_run, portal_block_mutation")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comments_review_id'), table_name='review_comments')
    op.drop_index('ix_review_comments_opp_version', table_name='review_comments')
    op.drop_table('review_comments')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ai_findings_severity'), table_name='ai_findings')
    op.drop_index(op.f('ix_ai_findings_run_id'), table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index('ix_workflow_history_opp_time', table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_opportunity_documents_version_id'), table_name='opportunity_documents')
    op.drop_index(op.f('ix_opportunity_documents_logical_document_id'), table_name='opportunity_documents')
    op.drop_index('ix_documents_opp_active', table_name='opportunity_documents', postgresql_where='deleted_at IS NULL')
    op.drop_table('opportunity_documents')
    op.drop_index('ix_deliveries_pending', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_director_reviews_opportunity_id'), table_name='director_reviews')
    op.drop_table('director_reviews')
    op.drop_table('deepdive_data')
    op.drop_index('ix_ai_runs_opp_time', table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_version_id'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    op.drop_index(op.f('ix_opportunity_versions_opportunity_id'), table_name='opportunity_versions')
    op.drop_table('opportunity_versions')
    op.drop_index(op.f('ix_opportunity_access_user_id'), table_name='opportunity_access')
    op.drop_table('opportunity_access')
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where='read_at IS NULL')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_time', table_name='audit_logs')
    op.drop_index('ix_audit_opportunity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_opportunities_updated_at', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_team_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_owner_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_ai_readiness'), table_name='opportunities')
    op.drop_index('ix_opportunities_account_lower', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('ai_settings')
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('roles')
    # ### end Alembic commands ###
