"""ai ingestion and jobs

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-18 10:57:29.824873
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector must exist before the chunk table. Creating an extension needs elevated rights, so if the
    # database user cannot do it, fail with instructions rather than a bare permission error.
    bind = op.get_bind()
    installed = bind.exec_driver_sql("SELECT 1 FROM pg_extension WHERE extname = 'vector'").first()
    if not installed:
        try:
            op.execute("CREATE EXTENSION vector")
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                "The pgvector extension is required for AI retrieval but this database user cannot create it. "
                "Ask a superuser to run: CREATE EXTENSION vector;  (CloudNativePG: add it to spec.postgresql.shared_preload "
                "or run it once as the postgres role.)"
            ) from exc
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=80), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name=op.f('ck_ai_jobs_status')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_ai_jobs_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ai_analysis_runs.id'], name=op.f('fk_ai_jobs_run_id_ai_analysis_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_ai_jobs_version_id_opportunity_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_jobs'))
    )
    op.create_index('ix_ai_jobs_claim', 'ai_jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_ai_jobs_run_id'), 'ai_jobs', ['run_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('document_category', sa.String(length=40), nullable=True),
    sa.Column('field_path', sa.String(length=160), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=120), nullable=True),
    sa.Column('section_path', sa.String(length=400), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('location_label', sa.String(length=600), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_kind IN ('document','deepdive','review')", name=op.f('ck_document_chunks_source_kind')),
    sa.ForeignKeyConstraint(['document_id'], ['opportunity_documents.id'], name=op.f('fk_document_chunks_document_id_opportunity_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_document_chunks_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['opportunity_versions.id'], name=op.f('fk_document_chunks_version_id_opportunity_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index('ix_chunks_fts', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_version_source', 'document_chunks', ['version_id', 'source_kind'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_foreign_key('fk_opportunities_current_version', 'opportunities', 'opportunity_versions', ['current_version_id'], ['id'], use_alter=True)
    op.create_foreign_key(op.f('fk_teams_director_id_users'), 'teams', 'users', ['director_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE FUNCTION portal_chunk_search_vector() RETURNS trigger AS $$
        BEGIN
          NEW.search_vector := to_tsvector('simple', coalesce(NEW.text, ''));
          RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER document_chunks_search_vector BEFORE INSERT OR UPDATE OF text ON document_chunks
        FOR EACH ROW EXECUTE FUNCTION portal_chunk_search_vector();
    """)
    op.execute("CREATE INDEX ix_chunks_embedding ON document_chunks USING hnsw (embedding vector_cosine_ops)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_chunks_embedding")
    op.execute("DROP TRIGGER IF EXISTS document_chunks_search_vector ON document_chunks")
    op.execute("DROP FUNCTION IF EXISTS portal_chunk_search_vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_director_id_users'), 'teams', type_='foreignkey')
    op.drop_constraint('fk_opportunities_current_version', 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('ix_chunks_version_source', table_name='document_chunks')
    op.drop_index('ix_chunks_fts', table_name='document_chunks', postgresql_using='gin')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_ai_jobs_run_id'), table_name='ai_jobs')
    op.drop_index('ix_ai_jobs_claim', table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
