"""roles, portfolio manager and director

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-18 16:16:41.123668
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Role keys change with the new organisation model; existing users keep their access.
    op.execute("ALTER TABLE roles DROP CONSTRAINT IF EXISTS ck_roles_role_key")
    op.execute("UPDATE roles SET key = 'portfolio_director', name = 'Portfolio Presales Director' WHERE key = 'presales_director'")
    op.execute("UPDATE roles SET key = 'presales_account', name = 'Presales Account' WHERE key = 'account_presales'")
    op.execute("""
        INSERT INTO roles (id, key, name)
        SELECT 5, 'portfolio_manager', 'Portfolio Presales Manager'
        WHERE NOT EXISTS (SELECT 1 FROM roles WHERE key = 'portfolio_manager')
    """)
    op.execute("""
        ALTER TABLE roles ADD CONSTRAINT ck_roles_role_key
        CHECK (key IN ('admin','presales_gm','portfolio_director','portfolio_manager','presales_account'))
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('opportunities', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('opportunities', sa.Column('director_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_opportunities_director_id'), 'opportunities', ['director_id'], unique=False)
    op.create_index(op.f('ix_opportunities_manager_id'), 'opportunities', ['manager_id'], unique=False)
    op.create_foreign_key(op.f('fk_opportunities_manager_id_users'), 'opportunities', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(op.f('fk_opportunities_director_id_users'), 'opportunities', 'users', ['director_id'], ['id'])
    op.add_column('teams', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_teams_manager_id_users'), 'teams', 'users', ['manager_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###

    # Existing opportunities keep their review line: the director of the team they belong to.
    op.execute("""
        UPDATE opportunities o SET director_id = t.director_id, manager_id = t.manager_id
        FROM teams t WHERE t.id = o.team_id
    """)


def downgrade() -> None:
    op.execute("UPDATE roles SET key = 'presales_director', name = 'Presales Director' WHERE key = 'portfolio_director'")
    op.execute("UPDATE roles SET key = 'account_presales', name = 'Account Presales' WHERE key = 'presales_account'")
    op.execute("DELETE FROM roles WHERE key = 'portfolio_manager'")
    op.execute("ALTER TABLE roles DROP CONSTRAINT IF EXISTS ck_roles_role_key")
    op.execute("""ALTER TABLE roles ADD CONSTRAINT ck_roles_role_key
                  CHECK (key IN ('admin','presales_gm','presales_director','account_presales'))""")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_manager_id_users'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'manager_id')
    op.drop_constraint(op.f('fk_opportunities_director_id_users'), 'opportunities', type_='foreignkey')
    op.drop_constraint(op.f('fk_opportunities_manager_id_users'), 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_manager_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_director_id'), table_name='opportunities')
    op.drop_column('opportunities', 'director_id')
    op.drop_column('opportunities', 'manager_id')
    op.create_index(op.f('ix_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
