"""opportunity type and vertical

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-28 08:19:01.002547
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('opportunity_type', sa.String(length=60), nullable=True))
    op.add_column('opportunities', sa.Column('vertical', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'vertical')
    op.drop_column('opportunities', 'opportunity_type')
    # ### end Alembic commands ###
